/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as ConceptsRouteImport } from './routes/concepts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWatchlistRouteImport } from './routes/api/watchlist'
import { Route as ApiPricesRouteImport } from './routes/api/prices'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiChainsRouteImport } from './routes/api/chains'
import { Route as ApiWatchlistCoinIdRouteImport } from './routes/api/watchlist/$coinId'
import { Route as ApiChainsIdRouteImport } from './routes/api/chains/$id'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsRoute = ConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchlistRoute = ApiWatchlistRouteImport.update({
  id: '/api/watchlist',
  path: '/api/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPricesRoute = ApiPricesRouteImport.update({
  id: '/api/prices',
  path: '/api/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChainsRoute = ApiChainsRouteImport.update({
  id: '/api/chains',
  path: '/api/chains',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWatchlistCoinIdRoute = ApiWatchlistCoinIdRouteImport.update({
  id: '/$coinId',
  path: '/$coinId',
  getParentRoute: () => ApiWatchlistRoute,
} as any)
const ApiChainsIdRoute = ApiChainsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiChainsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
  '/prices': typeof PricesRoute
  '/simulator': typeof SimulatorRoute
  '/api/chains': typeof ApiChainsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/api/chains/$id': typeof ApiChainsIdRoute
  '/api/watchlist/$coinId': typeof ApiWatchlistCoinIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
  '/prices': typeof PricesRoute
  '/simulator': typeof SimulatorRoute
  '/api/chains': typeof ApiChainsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/api/chains/$id': typeof ApiChainsIdRoute
  '/api/watchlist/$coinId': typeof ApiWatchlistCoinIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concepts': typeof ConceptsRoute
  '/prices': typeof PricesRoute
  '/simulator': typeof SimulatorRoute
  '/api/chains': typeof ApiChainsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/prices': typeof ApiPricesRoute
  '/api/watchlist': typeof ApiWatchlistRouteWithChildren
  '/api/chains/$id': typeof ApiChainsIdRoute
  '/api/watchlist/$coinId': typeof ApiWatchlistCoinIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concepts'
    | '/prices'
    | '/simulator'
    | '/api/chains'
    | '/api/health'
    | '/api/prices'
    | '/api/watchlist'
    | '/api/chains/$id'
    | '/api/watchlist/$coinId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/concepts'
    | '/prices'
    | '/simulator'
    | '/api/chains'
    | '/api/health'
    | '/api/prices'
    | '/api/watchlist'
    | '/api/chains/$id'
    | '/api/watchlist/$coinId'
  id:
    | '__root__'
    | '/'
    | '/concepts'
    | '/prices'
    | '/simulator'
    | '/api/chains'
    | '/api/health'
    | '/api/prices'
    | '/api/watchlist'
    | '/api/chains/$id'
    | '/api/watchlist/$coinId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConceptsRoute: typeof ConceptsRoute
  PricesRoute: typeof PricesRoute
  SimulatorRoute: typeof SimulatorRoute
  ApiChainsRoute: typeof ApiChainsRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPricesRoute: typeof ApiPricesRoute
  ApiWatchlistRoute: typeof ApiWatchlistRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts': {
      id: '/concepts'
      path: '/concepts'
      fullPath: '/concepts'
      preLoaderRoute: typeof ConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchlist': {
      id: '/api/watchlist'
      path: '/api/watchlist'
      fullPath: '/api/watchlist'
      preLoaderRoute: typeof ApiWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prices': {
      id: '/api/prices'
      path: '/api/prices'
      fullPath: '/api/prices'
      preLoaderRoute: typeof ApiPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chains': {
      id: '/api/chains'
      path: '/api/chains'
      fullPath: '/api/chains'
      preLoaderRoute: typeof ApiChainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/watchlist/$coinId': {
      id: '/api/watchlist/$coinId'
      path: '/$coinId'
      fullPath: '/api/watchlist/$coinId'
      preLoaderRoute: typeof ApiWatchlistCoinIdRouteImport
      parentRoute: typeof ApiWatchlistRoute
    }
    '/api/chains/$id': {
      id: '/api/chains/$id'
      path: '/$id'
      fullPath: '/api/chains/$id'
      preLoaderRoute: typeof ApiChainsIdRouteImport
      parentRoute: typeof ApiChainsRoute
    }
  }
}

interface ApiChainsRouteChildren {
  ApiChainsIdRoute: typeof ApiChainsIdRoute
}

const ApiChainsRouteChildren: ApiChainsRouteChildren = {
  ApiChainsIdRoute: ApiChainsIdRoute,
}

const ApiChainsRouteWithChildren = ApiChainsRoute._addFileChildren(
  ApiChainsRouteChildren,
)

interface ApiWatchlistRouteChildren {
  ApiWatchlistCoinIdRoute: typeof ApiWatchlistCoinIdRoute
}

const ApiWatchlistRouteChildren: ApiWatchlistRouteChildren = {
  ApiWatchlistCoinIdRoute: ApiWatchlistCoinIdRoute,
}

const ApiWatchlistRouteWithChildren = ApiWatchlistRoute._addFileChildren(
  ApiWatchlistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConceptsRoute: ConceptsRoute,
  PricesRoute: PricesRoute,
  SimulatorRoute: SimulatorRoute,
  ApiChainsRoute: ApiChainsRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiPricesRoute: ApiPricesRoute,
  ApiWatchlistRoute: ApiWatchlistRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
